name: products
authors:
  - Adam Whitcroft
date_added: 2018-11-14
date_modified: 2018-11-14
description: >
  Used to help direct merchants to the products page.
exclusive_use:
public: true
set: major
style: twotone
version: 1
keywords:
  - tag
  - products
  - goods
