authors:
  - adam.whitcoft <adam.whitcroft@shopify.com>
date_added: 27-11-2018
description: "A price tag symbol used to represent products"
exclusive: false
major: false
keywords: 
  - tag
  - products
  - goods
