authors:
  - adam.whitcoft <adam.whitcroft@shopify.com>
date_added: 2018-11-14
date_modified: 2018-11-14
description: >
    A price tag symbol used to represent products
exclusive_use:
public: false
set: Major
monotone: true
version: 1
keywords:
  - tag
  - products
  - goods
