name: settings
set: major
description:
  Used to represent settings or a configuration option.
keywords:
  - configure
  - settings
  - cog
authors:
  - Adam Whitcroft
public: true
version: 1
date_added: 2019-03-15
date_modified: 2019-03-15
exclusive_use:
