name: polaris-icons
up:
  - node:
      yarn: true
      version: v10.13.0 # to be kept in sync with .nvmrc and .circleci/config.yml

open:
  shipit: https://shipit.shopify.io/shopify/polaris-icons/testing
