name: polaris-icons
up:
  - node:
      yarn: true
      version: v10.13.0 # to be kept in sync with .nvmrc and .shopify-build/polaris-icons.yml

open:
  shipit: https://shipit.shopify.io/shopify/polaris-icons/testing
commands:
  test:
    run: yarn run test
  start:
    run: yarn run start
  server:
    run: yarn run develop
