# https://services.shopify.io/services/polaris-icons/testing
org_line: Shopify Core
owners:
  - Shopify/polaris
classification: tier4
url: https://polaris-icons.shopify.com
ci_url: https://buildkite.com/shopify/polaris-icons
slack_channels:
  - polaris-icons
  - polaris-icon-guild
security:
  data_management:
    contains_pii: false
